[tool.poetry]
name = "pitxu"
version = "0.1.0"
description = "Chatbot for the Raspberry Pi Zero 2w"
authors = ["Xavi <xavi@arnaus.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyxavi = "^0.8"
google-genai = "^1.16"
python-dotenv = "^1.1"
spidev = [{version="^3.7", markers="sys_platform=='linux'"}]
gpiozero = [{version="^2.0", markers="sys_platform=='linux'"}]
"rpi.gpio" = [{version="^0.7", markers="sys_platform=='linux'"}]
lgpio = [{version="^0.2.2.0", markers="sys_platform=='linux'"}]
pillow = "^11.2.1"
emoji = "^2.14.1"
pyaudio = "^0.2.14"
sounddevice = "^0.5.2"
vosk = [
    {url = "https://github.com/alphacep/vosk-api/releases/download/v0.3.42/vosk-0.3.42-py3-none-macosx_10_6_universal2.whl", markers="sys_platform=='darwin'"},
    {url = "https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-0.3.45-py3-none-manylinux2014_aarch64.whl", markers="sys_platform=='linux'"}
]
numpy = "^2.2.6"
piper-phonemize-fix = [
    {url = "https://files.pythonhosted.org/packages/a9/a9/af72e1f392128485c534a7af535b0ccd4ea4f7c81718a168af6ade0c54b3/piper_phonemize_fix-1.2.1-cp311-cp311-macosx_10_14_x86_64.whl", markers="sys_platform=='darwin'"}
    {url = "https://files.pythonhosted.org/packages/7a/8c/a9cf9b911232ddc1f9ce65f9eb55b82df1fa709da5a0bcae653f78a9f326/piper_phonemize_fix-1.2.1-cp313-cp313-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl", markers="sys_platform=='linux'"}
]
onnxruntime = "^1.22.0"

[tool.poetry.scripts]
main = "runner:run"

[virtualenvs.options]
system-site-packages = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
