[tool.poetry]
name = "pitxu"
version = "0.1.0"
description = "Chatbot for the Raspberry Pi Zero 2w"
authors = ["Xavi <xavi@arnaus.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyxavi = "^1.1.0"
multiprocessing-logging = "^0.3.4"
google-genai = "^1.16"
python-dotenv = "^1.1"
spidev = [{version="^3.7", markers="sys_platform=='linux'"}]
gpiozero = [{version="^2.0", markers="sys_platform=='linux'"}]
"rpi.gpio" = [{version="^0.7", markers="sys_platform=='linux'"}]
lgpio = [{version="^0.2.2.0", markers="sys_platform=='linux'"}]
pillow = "^11.2.1"
emoji = "^2.15.0"
pyaudio = "^0.2.14"
sounddevice = "^0.5.2"
vosk = [
    {url = "https://github.com/alphacep/vosk-api/releases/download/v0.3.42/vosk-0.3.42-py3-none-macosx_10_6_universal2.whl", markers="sys_platform=='darwin'"},
    {url = "https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-0.3.45-py3-none-manylinux2014_aarch64.whl", markers="sys_platform=='linux'"}
]
piper-tts = [{version="^1.3.0", markers="sys_platform=='linux'"}]
psutil = "^7.0.0"
"luma.led_matrix" = "^1.7.1"
numpy = "^2.3.4"
onnxruntime = "^1.23.2"

[tool.poetry.scripts]
main = "runner:run"
sounddevices = "runner:query_sound_devices"
clear = "runner:clear_displays"
test_matrix = "runner:test_matrix"

[tool.poetry.requires-plugins]
poetry-plugin-shell = ">=1.0.1"
poetry-plugin-export = ">=1.8"

[virtualenvs.options]
system-site-packages = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
