[tool.poetry]
name = "pitxu"
version = "0.3.6"
description = "Chatbot for the Raspberry Pi 5"
authors = ["Xavi <xavi@arnaus.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyxavi = "^1.3.1"
google-genai = "^1.16"
python-dotenv = "^1.1"
spidev = [{version="^3.7", markers="sys_platform=='linux'"}]
gpiozero = [{version="^2.0", markers="sys_platform=='linux'"}]
rpi-lgpio = [{version="^0.6", markers="sys_platform=='linux'"}]
lgpio = [{version="^0.2.2.0", markers="sys_platform=='linux'"}]
pillow = "^12.0.0"
emoji = "^2.15.0"
pyaudio = "^0.2.14"
sounddevice = "^0.5.2"
vosk = [
    {url = "https://github.com/alphacep/vosk-api/releases/download/v0.3.42/vosk-0.3.42-py3-none-macosx_10_6_universal2.whl", markers="sys_platform=='darwin'"},
    {url = "https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-0.3.45-py3-none-manylinux2014_aarch64.whl", markers="sys_platform=='linux'"}
]
numpy = "^2.3.4"
onnxruntime = [{version="^1.23.2", markers="sys_platform=='darwin'"}]
piper-tts = [{version="^1.3.0", markers="sys_platform=='linux'"}]
psutil = "^7.0.0"
"luma.led_matrix" = "^1.7.1"
ipdata = "^4.0.7"
geopy = "^2.4.1"
gemini-tool-agent = "^0.1.5"
fastmcp = "^2.13.1"
nest-asyncio = "^1.6.0"
flask = {extras = ["async"], version = "^3.1.2"}
pynput = "^1.8.1"
rpi-hardware-pwm = "^0.3.1"
ifcfg = "^0.24"
soundfile = "^0.13.1"
apscheduler = "^3.11.2"
macwifi = [{version="^0.0.5", markers="sys_platform=='darwin'"}]
scipy = "^1.17.1"
rms-vad = {extras = ["numpy"], version="^0.2.0"}
samplerate = "^0.2.4"
matplotlib = "^3.10.8"
openai-whisper = "^20250625"
faster-whisper = "^1.2.1"

[tool.poetry.scripts]
main = "runner:run"
test = "runner:tests"
util = "runner:utils"

[tool.poetry.requires-plugins]
poetry-plugin-shell = ">=1.0.1"
poetry-plugin-export = ">=1.8"

[virtualenvs.options]
system-site-packages = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
