from __future__ import annotations

from pitxu.lib.objects.function_call import FunctionCallHistory
from google.genai.chats import GenerateContentResponse
from google.genai.types import FinishReason, GenerateContentResponseUsageMetadata

from pyxavi import dd

class ChatbotResponse:

    text: str = ""
    function_call_history: FunctionCallHistory = FunctionCallHistory()
    error: FinishReason = None
    metadata: GenerateContentResponseUsageMetadata = None

    def __init__(self, text: str = "", function_call_history: FunctionCallHistory = None, error: FinishReason = None, metadata: GenerateContentResponseUsageMetadata = None):
        self.text = text
        self.function_call_history = function_call_history if function_call_history is not None else FunctionCallHistory()
        self.error = error
        self.metadata = metadata

    def set_text(self, text: str):
        self.text = text

    def set_function_call_history(self, function_call_history: FunctionCallHistory):
        self.function_call_history = function_call_history
    
    def set_error(self, error: FinishReason):
        self.error = error
    
    @staticmethod
    def from_response(response: GenerateContentResponse) -> ChatbotResponse: 
        return ChatbotResponse(
            text=response.text,
            function_call_history=FunctionCallHistory.from_response(response),
            error=ChatbotResponse.parse_error(response),
            metadata=ChatbotResponse.parse_metadata(response)
        )

    @staticmethod
    def parse_error(response: GenerateContentResponse) -> FinishReason:
        """
        Parses the given response to determine if there was an error.
        It all starts by checking if there is a text in the answer.

        Args:
            response (GenerateContentResponse): The response to parse.
        Returns:
            FinishReason: The finish reason indicating an error, or None if no error.
        
        FINISH_REASON_UNSPECIFIED: The finish reason is unspecified.
        STOP: Token generation reached a natural stopping point or a configured stop sequence.
        MAX_TOKENS: Token generation reached the configured maximum output tokens.
        SAFETY: Token generation stopped because the content potentially contains safety violations. NOTE: When streaming, [content][] is empty if content filters blocks the output.
        RECITATION: The token generation stopped because of potential recitation.
        LANGUAGE: The token generation stopped because of using an unsupported language.
        OTHER: All other reasons that stopped the token generation.
        BLOCKLIST: Token generation stopped because the content contains forbidden terms.
        PROHIBITED_CONTENT: Token generation stopped for potentially containing prohibited content.
        SPII: Token generation stopped because the content potentially contains Sensitive Personally Identifiable Information (SPII).
        MALFORMED_FUNCTION_CALL: The function call generated by the model is invalid.
        IMAGE_SAFETY: Token generation stopped because generated images have safety violations.
        UNEXPECTED_TOOL_CALL: The tool call generated by the model is invalid.
        IMAGE_PROHIBITED_CONTENT: Image generation stopped because the generated images have prohibited content.
        NO_IMAGE: The model was expected to generate an image, but none was generated.
        """

        try:
            # First, check if there is any text at all
            if response.text and len(response.text.strip()) > 0:
                return None

            # Assume the first candidate is representative
            # Then, take the finish_reason. If not None then it's an error.
            finish_reason: FinishReason = None
            if response.candidates and len(response.candidates) > 0:
                finish_reason = response.candidates[0].finish_reason

            if finish_reason is not None:
                return finish_reason

        except Exception as e:
            return "Failed to parse the response searching for errors due to: " + str(e)
    
    @staticmethod
    def parse_metadata(response: GenerateContentResponse) -> GenerateContentResponseUsageMetadata:
        """
        Parses the given response to extract metadata.
        Args:
            response (GenerateContentResponse): The response to parse.
        Returns:
            dict: A dictionary containing metadata key-value pairs.
        """

        try:
            return response.usage_metadata
        except Exception as e:
            return None